langganan/urls.py
from django.urls import path
from . import views

app_name = 'langganan'

urlpatterns = [
    path('langganan_paket/', views.langganan_paket, name='langganan_paket'),
    path('riwayat_transaksi/', views.riwayat_transaksi, name='riwayat_transaksi'),
    path('pembayaran_paket/<str:jenis>/', views.pembayaran_paket, name='pembayaran_paket'),
]

main/urls.py
from django.urls import path
from main.views import show_main
from main.views import show_main,  play_song, play_user_playlist, register_user, register_label, home, login_and_register
from main.views import register , dashboard
from main.views import login_user
from main.views import logout_user
from main.views import search
from main.views import createpod
from .views import createpodepisode
from main.views import seechart
from main.views import daily
from main.views import weekly
from main.views import monthly
from main.views import yearly
from main.views import download_song, add_song_to_playlist, user_play_song, shuffle_playlist

app_name = 'main'

urlpatterns = [
    path('', show_main, name='show_main'),
    path('register/', register, name='register'),
    path('login/', login_user, name='login'),
    path('logout/', logout_user, name='logout'),
    path('search/', search, name='search'),
    path('play-song/<str:id>/', play_song, name='play_song'),
    path('play-user-playlist/<str:id>/', play_user_playlist, name='play_user_playlist'),    
    path('createpod.html/', createpod, name='createpod'),
    path('createpod.html/createpod_episode.html/', createpodepisode, name='createpodepisode'),
    path('seechart.html/', seechart, name='seechart'),
    path('seechart.html/daily.html', daily, name='daily'),
    path('seechart.html/weekly.html', weekly, name='weekly'),
    path('seechart.html/monthly.html', monthly, name='monthly'),
    path('seechart.html/yearly.html', yearly, name='yearly'),
    path('register/user/', register_user, name='register_user'),
    path('register/label/', register_label, name='register_label'),
    path('home/', home, name='home'),
    path('login_and_register/', login_and_register, name='login_and_register'),
    path('dashboard/', dashboard, name='dashboard'),
    path('download-song/<str:id>/', download_song, name='download_song'),
    path('add-song-to-playlist/', add_song_to_playlist, name='add_song_to_playlist'),
    path('user-play-song/<str:id>/', user_play_song, name='user_play_song'),
    path('shuffle-playlist/<str:id>/', shuffle_playlist, name='shuffle_playlist')
]

marmut/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('playlist/', include('playlist.urls')),
    path('langganan/', include(('langganan.urls', 'langganan'), namespace='langganan')),
    path('song/', include('song.urls')),
    path('royalty_management/', include(('royalty_management.urls', 'royalty_management'), namespace='royalty_management')),
]

royalty_management/urls.py
from django.urls import path
from .views import view_royalty, create_album, create_song, view_album, view_album_label, view_album_detail, view_song_detail, delete_album, delete_song

urlpatterns = [
    path('view_royalty/', view_royalty, name='view_royalty'),
    path('create_album/', create_album, name='create_album'),
    path('create_song/<uuid:album_id>/', create_song, name='create_song'),
    path('view_album/', view_album, name='view_album'),
    path('view_album_label/', view_album_label, name='view_album_label'),
    path('view_album_detail/<uuid:album_id>/', view_album_detail, name='view_album_detail'),
    path('view_song_detail/<uuid:song_id>/', view_song_detail, name='view_song_detail'),
    path('delete_album/<uuid:album_id>/', delete_album, name='delete_album'),
    path('delete_song/<uuid:song_id>/', delete_song, name='delete_song'),
]

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Marmut</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet">
    <style>
        body, .form-label, .btn {
            background-color: #121212; 
            color: #fff; 
        }
        h2 {
            color: #fff; 
        }
        .form-box {
            background-color: #333;
            padding: 20px;
            border-radius: 8px;
            border: 1px solid #444;
            box-shadow: 0 4px 8px rgba(0,0,0,0.5);
        }
        .btn-pink {
            background-color: #ff007f; 
            border-color: #ff007f;
        }
        .btn-pink:hover {
            background-color: #e60074;
            border-color: #cc0066;
        }
        .btn-cyan {
            background-color: #00ffff; 
            border-color: #00ffff;
        }
        .btn-cyan:hover {
            background-color: #00e5e5;
            border-color: #00cccc;
        }
        .form-control {
            background-color: #222;
            border: 1px solid #555;
            color: #fff;
        }
        .form-control:focus {
            box-shadow: 0 0 0 0.25rem rgba(0, 255, 255, 0.25);
            border-color: #00ffff;
        }
    </style>
</head>
<body>
    {% include 'navbar_user.html' %}

    <div class="container mt-4">
        {% block content %}{% endblock %}
    </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>

templates/navbar.html
<nav class="navbar navbar-expand-md navbar-dark bg-dark-custom">
    <div class="container-fluid">
        <a class="navbar-brand" href="#">Mahmud</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav me-auto mb-2 mb-md-0">
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="#">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">Pricing</a>
                </li>
            </ul>
            <form class="d-flex">
                <a href="{% url 'main:login' %}" class="btn btn-pink me-2" type="submit">Login</a>
                <a href="{% url 'main:register' %}" class="btn btn-cyan" type="submit">Register</a>
            </form>
        </div>
    </div>
</nav>

templates/navbar_guest.html
<nav class="navbar navbar-expand-md navbar-dark bg-dark-custom">
    <div class="container-fluid">
        <a class="navbar-brand" href="#">Marmut</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav me-auto mb-2 mb-md-0">
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="#">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">Pricing</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'playlist_list' %}">Kelola Playlist</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'langganan_paket' %}">Langganan Paket</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'song_list' %}">Daftar Lagu</a>
                </li>
                <li>
                    <form class="d-flex" action="{% url 'main:search' %}" method="get">
                        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search" name="query">
                        <button class="btn btn-outline-success" type="submit">Search</button>
                    </form>
                </li>                
            </ul>
            <form class="d-flex">
                <a href="{% url 'main:login' %}" class="btn btn-pink me-2" type="submit">Login</a>
                <a href="{% url 'main:register' %}" class="btn btn-cyan" type="submit">Register</a>
            </form>
        </div>
    </div>
</nav>

templates/navbar_user.html
<nav class="navbar navbar-expand-md navbar-dark bg-dark-custom">
    <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'main:home' %}">Mahmud</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav me-auto mb-2 mb-md-0">
                {% if not navbar.is_guest %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'main:dashboard' %}">Dashboard</a>
                    </li>
                    {% if navbar.is_user or navbar.is_artist or navbar.is_songwriter or navbar.is_podcaster %}
                        <li class="nav-item">
                            <a class="nav-link" href="#">Chart</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#">Search Bar</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'playlist_list' %}">Kelola Playlist</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'langganan:langganan_paket' %}">Langganan Paket</a>
                        </li>
                    {% endif %}
                    {% if navbar.is_premium %}
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'downloaded_songs' %}">Kelola Downloaded Songs</a>
                        </li>
                    {% endif %}
                    {% if navbar.is_podcaster %}
                        <li class="nav-item">
                            <a class="nav-link" href="#">Kelola Podcast</a>
                        </li>
                    {% endif %}
                    {% if navbar.is_artist or navbar.is_songwriter %}
                        <!--Test Deployan up to date atau nggak-->
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'royalty_management:view_album' %}">Kelola Album & Songs</a>
                        </li>
                    {% endif %}
                    {% if navbar.is_label %}
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'royalty_management:view_album_label' %}">Kelola Album</a>
                        </li>
                    {% endif %}
                    {% if navbar.is_artist or navbar.is_songwriter or navbar.is_label %}
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'royalty_management:view_royalty' %}">Cek Royalti</a>
                        </li>
                    {% endif %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'main:logout' %}">Logout</a>
                    </li>
                {% else %}
                    <li class="nav-item">
                        <a class="nav-link active" href="{% url 'main:home' %}">Home</a>
                    </li>
                {% endif %}
            </ul>
            <form class="d-flex" action="{% url 'main:search' %}" method="get">
                <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search" name="query">
                <button class="btn btn-outline-success" type="submit">Search</button>
            </form>
  
            {% if navbar.is_guest %}
                <form class="d-flex">
                    <button class="btn btn-pink me-2" type="button" onclick="location.href='{% url 'main:login' %}'">Login</button>
                    <button class="btn btn-cyan" type="button" onclick="location.href='{% url 'main:register' %}'">Register</button>
                </form>
            {% endif %}
        </div>
    </div>
</nav>

templates/search_results.html
{% extends 'base.html' %}

{% block content %}
<h2>Hasil Pencarian "{{ query }}"</h2>

{% if results %}
    <table class="table table-dark">
        <thead>
            <tr>
                <th>Tipe</th>
                <th>Judul</th>
                <th>Oleh</th>
                <th>Actions</th>
            </tr>
        </thead>
        <tbody>
            {% for result in results %}
                <tr>
                    <td>{{ result.type }}</td>
                    <td>{{ result.title }}</td>
                    <td>{{ result.by }}</td>
                    <td>
                        <a href="{{ result.url }}" class="btn btn-sm btn-info">Lihat</a>
                    </td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
{% else %}
    <p>Maaf, pencarian untuk "{{ query }}" tidak ditemukan</p>
{% endif %}
{% endblock %}